# Generated by Django 6.0.7 on 2026-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Si es False, el usuario debe ser aprobado por un supervisor para poder ingresar'),
        ),
    ]
