# Generated by Django 6.0.7 on 2026-08-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_assign_default_teams'),
        ('challenges', '0012_remove_challenge_team'),
        ('chat', '0005_remove_chatmessage_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='used_by',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamInvitation',
        ),
    ]
