# Generated by Django 6.0.7 on 2026-08-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_user_team_teaminvitation'),
        ('chat', '0002_chatreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.team'),
        ),
    ]
