# Generated by Django 6.0.7 on 2026-08-20 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_recipient(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    Challenge = apps.get_model('challenges', 'Challenge')
    ChallengeExpiryNotice = apps.get_model('challenges', 'ChallengeExpiryNotice')
    for notice in ChallengeExpiryNotice.objects.select_related('challenge').iterator():
        challenge = notice.challenge
        message = (
            ChatMessage.objects
            .filter(user_id=challenge.created_by_id, text__contains=challenge.title, recipient__isnull=True)
            .order_by('id')
            .first()
        )
        if message:
            message.recipient_id = notice.user_id
            message.save(update_fields=['recipient'])


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatmessage_team'),
        ('challenges', '0013_challengeexpirynotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Si se define, el mensaje es privado y solo lo ve ese usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_recipient, migrations.RunPython.noop),
    ]
