# Generated by Django 6.0.7 on 2026-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date',
            field=models.DateField(blank=True, help_text='Fecha límite del reto', null=True),
        ),
    ]
