# Generated by Django 6.0.7 on 2026-07-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_medal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='date',
        ),
        migrations.AddField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite del reto', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del reto', null=True),
        ),
    ]
