# Generated by Django 6.0.7 on 2026-07-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_challenge_date_challenge_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='video',
            field=models.FileField(blank=True, help_text='Video explicativo opcional del reto', null=True, upload_to='challenge_videos/'),
        ),
    ]
