# Generated by Django 6.0.7 on 2026-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0, help_text='Puntos asignados por el supervisor'),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='review_comment',
            field=models.TextField(blank=True, default='', help_text='Comentario del supervisor para el participante'),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
