# Generated by Django 6.0.7 on 2026-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_evidencelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('returned', 'Devuelto')], default='pending', max_length=20),
        ),
    ]
