# Generated by Django 6.0.7 on 2026-08-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_assign_default_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='team',
        ),
    ]
