# Generated by Django 6.0.7 on 2026-07-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypoint',
            name='comment',
        ),
        migrations.AddField(
            model_name='dailypoint',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
