# Generated by Django 6.0.7 on 2026-07-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_dailypoint_comment_dailypoint_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypoint',
            name='steps_image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/'),
        ),
    ]
