# Generated by Django 6.0.7 on 2026-08-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_dailypoint_steps_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypoint',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
