# Generated by Django 6.0.7 on 2026-09-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set(),
        ),
    ]
