# Generated by Django 6.0.7 on 2026-09-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='grasa',
            new_name='grasa_corporal',
        ),
        migrations.AddField(
            model_name='measurement',
            name='grasa_visceral',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grasa visceral', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto de las medidas', null=True, upload_to='measurements/'),
        ),
    ]
