# Generated by Django 6.0.7 on 2026-09-02 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_rename_grasa_measurement_grasa_corporal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_date', models.DateField(help_text='Fecha de la próxima medición')),
                ('interval_days', models.IntegerField(default=15, help_text='Días entre mediciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
