# Generated by Django 6.0.7 on 2026-09-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_measurementschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='musculo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Músculo en %', max_digits=5, null=True),
        ),
    ]
