# Generated by Django 6.0.7 on 2026-09-20 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_initial_measurement_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('daily_point', 'Registro diario'), ('bonus_points', 'Puntos bonus'), ('measurement_day', 'Día de medición')], max_length=30)),
                ('date', models.DateField(blank=True, help_text='Fecha afectada del registro', null=True)),
                ('comment', models.TextField(blank=True, default='', help_text='Comentario del admin explicando por qué se hizo')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Valores anteriores y nuevos para revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs_as_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
